#  Análise Exploratória da base Varejo

## 1. Script em Python para Análise Exploratória da base Varejo.

### Importando as blibliotecas necessárias.

In [92]:
# Importando bibliotecas do Python necessárias
import pandas as pd
import numpy as np
import csv

## Sprint 1 Realização da importação dos dados.

In [93]:
# Importando o arquivo
with open("base_varejo.csv", mode="r", encoding="utf-8") as arquivo:
    leitor = csv.DictReader(arquivo, delimiter=";")
    dados = list(leitor)  # Carrega os dados para uma lista

# Exibe o primeiro registro lido para confirmar
print(dados[0])

{'DATA': '01/02/2019', 'CO_ID': '1000', 'CL_ID': '534', 'CL_GENERO': 'M', 'CL_EC': '4', 'CL_FHL': '1', 'CL_SEG': 'C', 'PR_ID': '67', 'PR_CAT': 'BEBIDAS', 'PR_NOME': 'REFRIGERANTE GUARANA', '': ''}

### Utilizando o comando pd.read_csv para carregar o aruivo.

In [94]:
# Carregando o arquivo CSV para o DataFrame OBS: O arquivo CSV deve estar no mesmo diretório do notebook
df = pd.read_csv("base_varejo.csv", sep=";")

### Informações do Data Frame

In [95]:
# Exibir as primeiras linhas da tabela
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [96]:
# Verificando características do DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [97]:
#Exibindo as últimas linhas do DataFrame
df.tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [98]:
# Descrevendo estatísticas descritivas do DataFrame
df.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.000000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.089890,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.247541,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.000000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.000000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.000000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.000000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.000000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

## Sprint 2 Normalização dos dados

### A coluna Data esta o formato object. Vamos utilizar o Pandas para converter a coluna Data para o formato datetime. Assim é possível trabalhar as funcionalidades utilizando a coluna Data.

In [99]:
# 2. Converter a coluna DATA de 'object' para 'datetime'
df['DATA'] = pd.to_datetime(df['DATA'], dayfirst=True, errors='coerce')

In [100]:
# Verificando a conversão da coluna DATA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[ns]
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: datetime64[ns](1), float64(4), int64(5), object(4)
memory usage: 88.7+ MB

In [101]:
# Removendo espaços em branco na identificação das colunas do Data Frame
df.columns = df.columns.str.strip()

In [102]:
# Convertendo a coluna PR_CAT para string
df['PR_CAT'] = df['PR_CAT'].astype(str)

In [103]:
# Convertendo a coluna PR_NOME para string
df['PR_NOME'] = df['PR_NOME'].astype(str)

In [104]:
# Definindo a primeira letra de cada palavra em maiúscula para as colunas CL_GENERO, CL_SEG, PR_CAT e PR_NOME
df['CL_GENERO'] = df['CL_GENERO'].str.title()
df['CL_SEG']    = df['CL_SEG'].str.title()
df['PR_CAT']    = df['PR_CAT'].str.title()
df['PR_NOME']   = df['PR_NOME'].str.title()

In [105]:
# Removendo espaços em branco no início e no final das strings das colunas do Data Frame
df["CL_GENERO"] = df["CL_GENERO"].str.strip()
df["CL_SEG"]    = df["CL_SEG"].str.strip()
df["PR_CAT"]    = df["PR_CAT"].str.strip()
df["PR_NOME"]   = df["PR_NOME"].str.strip()

## Sprint 3 (Limpeza de Nulos e Duplicatas): Aplicação das condicionais e funções  para identificação e substituição de valores vazios e  de str para valores de data tipo datetime, na tabela de varejo.

In [106]:
# Retorna a quantidade de nulos por coluna
df.isna().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [107]:
# Retorna o total geral de nulos no DataFrame inteiro
df.isna().sum().sum()

3320000

In [108]:
# Conta textos vazios ou formados apenas por espaços nas colunas do tipo 'object'
df.select_dtypes(include='object').apply(lambda col: col.str.strip().eq('')).sum()

CL_GENERO    0
CL_SEG       0
PR_CAT       0
PR_NOME      0
dtype: int64

In [109]:
# Conta textos vazios ou formados apenas por espaços nas colunas do tipo 'object'
df.select_dtypes(include='object').apply(lambda col: col.str.strip().eq('')).sum()

CL_GENERO    0
CL_SEG       0
PR_CAT       0
PR_NOME      0
dtype: int64

In [110]:
# Verificando a quantidade de duplicatas no DataFrame
df.duplicated().sum()

96553

In [111]:
# O parâmetro keep=False mostra todas as ocorrências das linhas repetidas
df[df.duplicated(keep=False)]

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,2019-02-01,1000,534,M,4,1,C,4,Alimentos,Abacaxi,NaN,NaN,NaN,NaN
7,2019-02-01,1000,534,M,4,1,C,11,Alimentos,Azeite,NaN,NaN,NaN,NaN
14,2019-02-01,1000,534,M,4,1,C,13,Alimentos,Banana,NaN,NaN,NaN,NaN
15,2019-02-01,1000,534,M,4,1,C,218,Alimentos,Bife De Coxao Mole,NaN,NaN,NaN,NaN
19,2019-02-01,1000,534,M,4,1,C,13,Alimentos,Banana,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,2022-08-19,919822,155,F,2,0,B,34,Alimentos,Ketchup,NaN,NaN,NaN,NaN
829992,2022-08-19,919822,155,F,2,0,B,30,Alimentos,File De Peixe,NaN,NaN,NaN,NaN
829995,2022-08-19,919822,155,F,2,0,B,183,Alimentos,Ketchup,NaN,NaN,NaN,NaN
829996,2022-08-19,919822,155,F,2,0,B,56,Alimentos,Queijo Mussarela,NaN,NaN,NaN,NaN
829997,2022-08-19,919822,155,F,2,0,B,227,Alimentos,Arroz,NaN,NaN,NaN,NaN

In [112]:
# Removendo duplicatas do DataFrame, mantendo a primeira ocorrência.
df.drop_duplicates()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,2019-02-01,1000,534,M,4,1,C,67,Bebidas,Refrigerante Guarana,NaN,NaN,NaN,NaN
1,2019-02-01,1000,534,M,4,1,C,70,Bebidas,Refrigerante Outros,NaN,NaN,NaN,NaN
2,2019-02-01,1000,534,M,4,1,C,178,Higiene,Lenco Umedecido,NaN,NaN,NaN,NaN
3,2019-02-01,1000,534,M,4,1,C,4,Alimentos,Abacaxi,NaN,NaN,NaN,NaN
4,2019-02-01,1000,534,M,4,1,C,175,Limpeza,Limpador Multiuso,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829991,2022-08-19,919822,155,F,2,0,B,86,Higiene,Preservativo,NaN,NaN,NaN,NaN
829993,2022-08-19,919822,155,F,2,0,B,62,Alimentos,Snacks,NaN,NaN,NaN,NaN
829994,2022-08-19,919822,155,F,2,0,B,11,Alimentos,Azeite,NaN,NaN,NaN,NaN
829998,2022-08-19,919822,155,F,2,0,B,214,Alimentos,Cebola,NaN,NaN,NaN,NaN
829999,2022-08-19,919822,155,F,2,0,B,59,Alimentos,Salgadinho,NaN,NaN,NaN,NaN

## Sprint 4 Estatística Descritiva

In [113]:
# Função para saber quem compra mais por filho.
compras_por_filhos = (
    df.groupby("CL_FHL")
    .size()
    .reset_index(name="TOTAL_COMPRAS")
    .sort_values(by="TOTAL_COMPRAS", ascending=False)
)

print(compras_por_filhos)

   CL_FHL  TOTAL_COMPRAS
0       0         435501
2       2         106622
3       3         104685
1       1         102813
4       4          80379

In [114]:
# Quem compra mais por segmento.
compras_por_segmento = (
    df.groupby("CL_SEG")
    .size()
    .reset_index(name="TOTAL_COMPRAS")
    .sort_values(by="TOTAL_COMPRAS", ascending=False)
)

print(compras_por_segmento)

  CL_SEG  TOTAL_COMPRAS
1      B         530163
2      C         232101
0      A          67736

In [115]:
# Qual categoria de produto é mais vendida.
categorias_mais_vendidas = (
    df.groupby("PR_CAT")
    .size()
    .reset_index(name="TOTAL_VENDAS")
    .sort_values(by="TOTAL_VENDAS", ascending=False)
)

print(categorias_mais_vendidas)

       PR_CAT  TOTAL_VENDAS
2   Alimentos        434767
4     Higiene        155574
5     Limpeza        145754
3     Bebidas         43299
6         Pet         32399
1  Acessorios         14557
0        #N/D          3650

### Aplicando desconto promocional para a caterigora Acessorios. Para aumentar as vendas nessa categoria. Já que foi que obteve um número menor de vendas.

In [116]:
# Aplicando desconto e sinalizando a promoção para produtos da categoria "ACESSORIOS".
def verificar_promocao(linha):
    if linha['PR_CAT'] == 'ACESSORIOS':
        return 'Sim'
    else:
        return 'Não'

def calcular_desconto_acessorios(linha):
    if linha['PR_CAT'] == 'ACESSORIOS':
        return 0.10
    else:
        return 0.0

df['EM_PROMOCAO'] = df.apply(verificar_promocao, axis=1)
df['DESCONTO_PRODUTO'] = df.apply(calcular_desconto_acessorios, axis=1)

## Análisando métricas a partir da quantidade de filhos.

In [117]:
# Dados da coluna CL_FHL
df['CL_FHL'].describe()

count    830000.00000
mean          1.14654
std           1.41696
min           0.00000
25%           0.00000
50%           0.00000
75%           2.00000
max           4.00000
Name: CL_FHL, dtype: float64

In [118]:
# Estatísticas básicas da coluna CL_FHL
print("Média:", df['CL_FHL'].mean())          # Média aritmética
print("Mediana:", df['CL_FHL'].median())       # Valor central (50%)
print("Moda:", df['CL_FHL'].mode()[0])         # Quantidade de filhos mais comum
print("Desvio Padrão:", df['CL_FHL'].std())    # Variabilidade/dispersão dos dados
print("Mínimo:", df['CL_FHL'].min())           # Menor número de filhos
print("Máximo:", df['CL_FHL'].max())           # Maior número de filhos

Média: 1.1465397590361446
Mediana: 0.0
Moda: 0
Desvio Padrão: 1.416959527003528
Mínimo: 0
Máximo: 4

In [119]:
# Tabela com contagem total e percentual de clientes por quantidade de filhos
distribuicao = pd.DataFrame({
    'Qtd_Clientes': df['CL_FHL'].value_counts().sort_index(),
    'Percentual (%)': (df['CL_FHL'].value_counts(normalize=True).sort_index() * 100).round(2)
})

print(distribuicao)

        Qtd_Clientes  Percentual (%)
CL_FHL
0             435501           52.47
1             102813           12.39
2             106622           12.85
3             104685           12.61
4              80379            9.68

In [120]:
# Resumo estatístico de filhos agrupado por classe/segmento
filhos_por_classe = df.groupby('CL_SEG')['CL_FHL'].agg(
    media_filhos=('mean'),
    total_filhos=('sum'),
    qtd_clientes=('count')
).reset_index()

# Arredonda a média para 2 casas decimais
filhos_por_classe['media_filhos'] = filhos_por_classe['media_filhos'].round(2)

print(filhos_por_classe)

  CL_SEG  media_filhos  total_filhos  qtd_clientes
0      A          1.04         70373         67736
1      B          1.15        608092        530163
2      C          1.18        273163        232101

### Aplicando desconto proporcional a quantidade de filhos. A quantidade de pessoas com 4 filhor é a menor, por isso não afetará muito na receita final, mesmo com a aplicação do desconto.

In [121]:
# Aplicando desconto de 5%, no valor da compra total, para cada filho do cliente.

def calcular_desconto(linha):
    filhos = linha['CL_FHL']
    if filhos > 0:
        return filhos * 0.05
    else:
        return 0.0

# Criando coluna desconto
df['PERCENTUAL_DESCONTO'] = df.apply(calcular_desconto, axis=1)

# 3. Criar a nova tabela usando GROUPBY
tabela_desconto_por_filhos = df.groupby('CL_FHL').agg(
    PERCENTUAL_DESCONTO=('PERCENTUAL_DESCONTO', 'first'), 
    TOTAL_CLIENTES=('CL_FHL', 'count')                     
).reset_index()

# Exibindo a nova tabela
print(tabela_desconto_por_filhos)

   CL_FHL  PERCENTUAL_DESCONTO  TOTAL_CLIENTES
0       0                 0.00          435501
1       1                 0.05          102813
2       2                 0.10          106622
3       3                 0.15          104685
4       4                 0.20           80379

## Verificando qual foi o mês com menor quantidade de itens vendidos.

In [ ]:
# Data já foi convertida para datetime, agora vamos criar a coluna MES com o nome do mês correspondente.
# 
df["MES"] = df["DATA"].dt.month_name(locale="pt_BR")
vendas_por_mes = (
    df.groupby('MES')
    .size()
    .reset_index(name='TOTAL_VENDAS')
    .sort_values(by='TOTAL_VENDAS', ascending=True)
)

print(vendas_por_mes)

          MES  TOTAL_VENDAS
9    Novembro         40912
8       Março         64371
1      Agosto         65609
0       Abril         66935
6       Junho         67808
11   Setembro         68594
5       Julho         68983
2    Dezembro         70449
10    Outubro         73900
3   Fevereiro         76201
7        Maio         82275
4     Janeiro         83963

## Sprint 5 Relatório e Documentação:

### # Análise Exploratória de Dados - Varejo

Este repositório contém o projeto de Análise Exploratória de Dados (EDA) e higienização da base de dados de varejo composta por 830.000 registros. O estudo abrange desde o tratamento estrutural e limpeza de duplicadas até a geração de inteligência de negócios com regras de desconto e análise sazonal.

## Sobre o Projeto

O objetivo do projeto é transformar dados brutos de transações de varejo em insights estratégicos para a tomada de decisão. A análise identifica o comportamento de compra por perfil de cliente (estado civil, classe social e quantidade de filhos) e sazonalidade das vendas, propondo ações promocionais direcionadas para categorias de baixo desempenho.

## Principais Insights

* **Sazonalidade Crítica:** Novembro registrou o menor volume de vendas do ano (40.912 transações), enquanto Janeiro atingiu o ápice com 83.963 vendas.
* **Liderança por Categoria:** A categoria de **Alimentos** lidera com 434.767 vendas, ao passo que **Acessorios** apresentou o menor desempenho (14.557 itens), justificando uma campanha promocional com 10% de desconto.
* **Concentração de Segmento:** O **Segmento B** representa a maior fatia do volume de compras (530.163 transações), seguido pelo Segmento C (232.101) e Segmento A (67.736).
* **Perfil Familiar:** 52,47% dos clientes não possuem filhos. A média geral é de 1,15 filho por cliente, mantendo-se uniforme entre as classes sociais.
* **Viabilidade Promocional por Filhos:** A concessão de desconto de 5% por filho (com teto de 20% para 4 filhos) afeta a menor parcela da base, visto que clientes com 4 filhos correspondem a apenas 9,68% do total.
* **Qualidade dos Dados:** Identificou-se a presença de 96.553 linhas duplicadas e 4 colunas nulas (`Unnamed: 10` a `Unnamed: 13`), tratadas na fase de saneamento de dados.

## Sprints do Projeto

| **Sprint**   | **Etapa**               | **Descrição das Atividades**                                                                                               |
| ------------------ | ----------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- |
| **Sprint 1** | Importação dos Dados        | Leitura preliminar com`csv.DictReader`e carregamento do DataFrame via`pd.read_csv`com delimitador.                             |
| **Sprint 2** | Normalização                | Conversão da coluna`DATA`para`datetime`, remoção de espaços com`str.strip()`e padronização de maiúsculas/minúsculas. |
| **Sprint 3** | Limpeza de Nulos e Duplicatas | Mapeamento de valores nulos (`.isna()`)e remoção de 96.553 duplicatas com`df.drop_duplicates()`.                             |
| **Sprint 4** | Estatística Descritiva       | Agrupamento por segmento, categoria e número de filhos, além do cálculo das regras promocionais.                                |
| **Sprint 5** | Relatório & Documentação   | Consolidação dos indicadores finais de desempenho e elaboração da documentação técnica.                                     |
| **Sprint 6** | Versionamento                 | Publicação do código-fonte, dados limpos e documentação no repositório GitHub.                                               |

## Pré-requisitos e Configuração do VS Code

Para reproduzir ou contribuir com o projeto, siga o passo a passo para instalação e configuração do ambiente de desenvolvimento no  **Visual Studio Code** .

### 1. Instalação das Ferramentas Básicas

* **Python 3.11+** : Faça o download e instale a versão oficial do [Python](https://www.python.org/downloads/). Marque a opção **"Add Python to PATH"** durante a instalação.
* **VS Code** : Instale o editor de código oficial pelo site do [Visual Studio Code](https://code.visualstudio.com/).

### 2. Extensões Recomendadas no VS Code

Abra o VS Code, acesse o menu de extensões (`Ctrl + Shift + X` ou `Cmd + Shift + X` no macOS) e instale as seguintes extensões:

* **Python**  *(Microsoft)* : Adiciona suporte completo à linguagem Python, com suporte a autocompletar (IntelliSense) e depuração.
* **Jupyter**  *(Microsoft)* : Permite executar, editar e visualizar arquivos de Jupyter Notebook (`.ipynb`) diretamente no VS Code.
* **Data Wrangler**  *(Microsoft)* : Interface gráfica para exploração e limpeza rápida de dados integrada aos DataFrames do Pandas.
* **Office Viewer / Excel Viewer** : Permite visualizar e inspecionar planilhas `.csv` e `.xlsx` sem precisar sair do editor.

## Tecnologias e Bibliotecas Utilizadas

* **Python 3.11;**
* **Pandas** (Tratamento, agregação e manipulação de dados);
* **NumPy** (Apoio a cálculos estruturados);
* **Módulo CSV** (Leitura estruturada via dicionários);

## Como Executar

1. Clone o repositório para o seu ambiente local.
2. Posicione o arquivo `base_varejo.csv` no mesmo diretório do notebook `Mini_projeto.ipynb`.
3. Abra o VS Code na pasta do projeto e selecione o kernel Python configurado.
4. Execute as células do Jupyter Notebook sequencialmente da **Sprint 1** à **Sprint 6**.


## 📝 Licença

Este projeto está público.

## Sprint 6 Versionamento: Envio dos arquivos (script + README.md + df_limpo), via Git para o repositório no GitHub.

In [ ]:
# Exporta o DataFrame limpo/alterado para um novo arquivo CSV
df.to_csv("base_varejo_limpo.csv", sep=";", index=False, encoding="utf-8-sig")

print("Arquivo exportado com sucesso!")

### O Script do projeto, juntamente com README.md e o df_limpo estão disponíveis no GitHub.  Link: